# default muhplots configuration

# all worlds in which muhplots will be active
plotworlds:
  plotworld:
    # the maximum number of plots a player can own without the .unlimited permission
    max_per_player: 1
    # if a plot is unowned, should everyone be able to build on it?
    unprotected_are_public: true