# default muhplots configuration

plots:
# the maximum plot id which will be considered in a random plot search
  range: 3600
# the x/z dimensions of the plots
  size: 59
# the height of the walkway between the plots. used so that players can tp/find safely
  walkway_y: 12
# the region name prefix of the plots
  prefix: muhplot_
# the maximum plots a player can have without the .unlimited permission
  max_per_player: 1
# if a plot is unowned, should everyone be able to build on it?
  unprotected_are_public: true

# all worlds in which muhplots will be active
plotworlds:
  - plotworld