---
name: MuhPlots
main: de.chipf0rk.MuhPlots.MuhPlots
version: 0.0.1-SNAPSHOT
depend:
  - WorldGuard
  - WorldEdit
description: A plot manager that makes it possible for players and admins to protect and manage predefined WorldGuard plots in a simple way.
commands:
  mp:
    description: The master command that does everything. Yay!
    usage: §cWrong usage of the command! Type /plot help to get the full reference.
    aliases:
      - muhplot
      - muhplots
      - plot
permissions:
  mau5plots.protect:
    description: "Allows a player to protect an ownerless plot."
    default: true
  mau5plots.clear:
    description: "Allows a player (most likely administrator) to clear an owned plot, as in, make it owner- and memberless."
    default: false
  mau5plots.reset:
    description: "Allows a player (most likely administrator) to reset an owned plot, that means resetting the terrain without touching the owners."
    default: false
  mau5plots.delete:
    description: "Allows a player (most likely administrator) to delete an owned plot, that means resetting the terrain and owners."
    default: false
  mau5plots.find:
    description: "Allows a player to let the plugin find a free plot and teleports them to it."
    default: false
  mau5plots.unlimited:
    description: "Allows a player to bypass plot count limitation."
    default: false
  mau5plots.setowner:
    description: "Allows a player to protect a plot for another player."
    default: false
  mau5plots.*:
    description: "Gives all mau5plots permissions"
    children:
      mau5plots.protect: true
      mau5plots.clear: true
      mau5plots.reset: true
      mau5plots.delete: true
      mau5plots.find: true
      mau5plots.free: true
      mau5plots.unlimited: true
      mau5plots.setowner: true
      mau5plots.request: true
      mau5plots.accept: true
    default: false